version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=${ENVIRONMENT:-production}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      # PostgreSQL Configuration (External Proxmox Instance)
      - POSTGRES_HOST=${POSTGRES_HOST:-192.168.68.88}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-inventory_system}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # Weaviate Configuration (External Instance)
      - WEAVIATE_URL=${WEAVIATE_URL:-http://192.168.68.89:8080}
      - WEAVIATE_ENABLED=${WEAVIATE_ENABLED:-true}
      - WEAVIATE_TIMEOUT=${WEAVIATE_TIMEOUT:-30}
      - WEAVIATE_DEFAULT_LIMIT=${WEAVIATE_DEFAULT_LIMIT:-50}
      - WEAVIATE_DEFAULT_CERTAINTY=${WEAVIATE_DEFAULT_CERTAINTY:-0.7}
      # OpenAI Configuration (Embeddings API)
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      - EMBEDDING_DIMENSIONS=${EMBEDDING_DIMENSIONS:-1536}
      # Application Settings
      - DEBUG=${DEBUG:-false}
      - API_CORS_ORIGINS=${API_CORS_ORIGINS:-*}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - inventory_network

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://backend:8000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=true
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - inventory_network

networks:
  inventory_network:
    driver: bridge