"""Add item movement history table for audit trail

Revision ID: 37c062614055
Revises: 40eb957f8f3f
Create Date: 2025-07-01 08:13:00.514881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c062614055'
down_revision: Union[str, None] = '40eb957f8f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_movement_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('from_location_id', sa.Integer(), nullable=True),
    sa.Column('to_location_id', sa.Integer(), nullable=True),
    sa.Column('quantity_moved', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=True),
    sa.Column('quantity_after', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('system_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['from_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_movement_history_created_at'), 'item_movement_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_item_movement_history_id'), 'item_movement_history', ['id'], unique=False)
    op.create_index(op.f('ix_item_movement_history_item_id'), 'item_movement_history', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_movement_history_movement_type'), 'item_movement_history', ['movement_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_movement_history_movement_type'), table_name='item_movement_history')
    op.drop_index(op.f('ix_item_movement_history_item_id'), table_name='item_movement_history')
    op.drop_index(op.f('ix_item_movement_history_id'), table_name='item_movement_history')
    op.drop_index(op.f('ix_item_movement_history_created_at'), table_name='item_movement_history')
    op.drop_table('item_movement_history')
    # ### end Alembic commands ###
