"""fix_item_version_default

Revision ID: 952413129ffd
Revises: 49ee21527eeb
Create Date: 2025-06-30 13:00:00.030991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952413129ffd'
down_revision: Union[str, None] = '49ee21527eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'version',
               existing_type=sa.INTEGER(),
               server_default='1',
               existing_comment='Version number for optimistic locking',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Version number for optimistic locking',
               existing_nullable=False)
    # ### end Alembic commands ###
