"""Add category relationship to locations

Revision ID: ad4445d5f714
Revises: 15fd6a10550c
Create Date: 2025-06-29 15:14:38.509822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4445d5f714'
down_revision: Union[str, None] = '15fd6a10550c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_locations_category_id'), 'locations', ['category_id'], unique=False)
    op.create_foreign_key(None, 'locations', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_index(op.f('ix_locations_category_id'), table_name='locations')
    op.drop_column('locations', 'category_id')
    # ### end Alembic commands ###
